pipeline{
    environment{
        DOCKERHUB_CRED = credentials("Dockerhub-Credentials-ID")
    }
    agent any
    stages{
        
        stage("Stage 1 : Maven Build"){
            steps{
                dir('spe_mini_project'){
                    sh 'mvn clean install'
                }
                //builds jar file and runs all tests, creates target folder
            }
        }
        
        stage("Stage 2 : Build Docker Image"){
            steps{
                dir('spe_mini_project'){
                    sh "docker build -t sankalpkothari/calculator:latest ."
                }
            }
        }
        
        stage("Stage 3 : Push Docker Image to Dockerhub"){
            steps{
                sh 'echo $DOCKERHUB_CRED_PSW | docker login -u $DOCKERHUB_CRED_USR --password-stdin'
                sh "docker push sankalpkothari/calculator:latest"
            }
            //docker login and push image to dockerhub
        }
        
        stage("Stage 4 : Clean Unwanted Docker Images"){
            steps{
                sh "docker container prune -f"
                sh "docker image prune -a -f"
            }
            // clean unwanted docker images
        }
        
        stage('Stage 5 : Ansible Deployment') {
            steps {
                dir('spe_mini_project'){
                    sh 'ansible-playbook -i inventory Deploy-Calculator.yml'
                }
            }
        }
    }
}